version: "3"
services:
  privoxy:
    image: vimagick/privoxy
    container_name: privoxy
    restart: always
    ports:
      - 8118:8118
    volumes:
      - privoxy-data:/etc/privoxy
  
  ss:
    image: shadowsocks/shadowsocks-libev
    container_name: ss
    restart: always
    volumes:
      - $PWD:/conf
    command: ss-local -c conf/example.json


volumes:
  privoxy-data:
